name = Baseline
description = A simple 3 column Susy layout with a hero area and header and footer prefaces.
preview = preview.png
template = baseline-layout

; Regions
regions[branding]             = Branding
regions[header_preface_left]  = Header Preface Left
regions[header_preface_right] = Header Preface Right
regions[header]               = Header
regions[navigation]           = Navigation bar
regions[hero]                 = Hero
regions[highlighted]          = Highlighted
regions[help]                 = Help
regions[content]              = Content
regions[sidebar_first]        = First sidebar
regions[sidebar_second]       = Second sidebar
regions[footer_preface]       = Footer Preface
regions[footer_left]          = Footer Left
regions[footer_right]         = Footer Right

; Stylesheets
stylesheets[all][] = css/layouts/baseline/baseline.layout.css
stylesheets[all][] = css/layouts/baseline/baseline.layout.no-query.css
